config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  root 'static_pages#home'

  resources :admins, only: :index
  
  namespace :admins do
    resources :recipes, except: [:new, :show, :destroy]
    resources :food_items, except: [:new, :show, :destroy]
    resources :comments, only: :index
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :favorites
  end

  devise_for :users 

  devise_scope :user do
    get '/login/', to: 'devise/sessions#new', as: 'login'
    get '/signup', to: 'devise/registrations#new', as: 'signup'
    get '/settings', to: 'devise/registrations#edit', as: 'settings'
    get '/sign_in', to: 'devise/sessions#new'
  end

  resources :users

  resources :tags, only: [:index]
  resources :ingredients, only: [:autocomplete_food_item_name] do
    get :autocomplete_food_item_name, :on => :collection
  end

  resources :food_items

  resources :recipes do 
    resources :ingredients
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get 'tags/:tag' => 'recipes#index', as: :tag
  get 'ingredients/:ingredient' => 'recipes#index', as: :ingredient

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
  validates :user_id, presence: true
	validates :recipe_id, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
   validates :user_id, presence: true
  validates :recipe_id, presence: true
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :ingredients, dependent: :destroy
  has_many :recipes, through: :ingredients

 
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :food_item
  belongs_to :recipe

  def food_item_name
  	food_item.try(:name)
  end

  def food_item_name=(name)
  	self.food_item = FoodItem.find_or_create_by(name: name) if name.present?
  end

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :ingredients, dependent: :destroy
  has_many :food_items, through: :ingredients
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :instructions, dependent: :destroy

  has_attached_file :image
  validates_attachment :image, 
    :content_type => { :content_type => ['image/jpeg', 'image/png']},
    :size => { :less_than => 5.megabyte }

  validates :name, presence: true
    
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc { |a| a[:food_item_name].blank? }

  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: proc { |a| a[:content].blank? }

  def self.tagged_with(name)
    Tag.find_by!(name: name).recipes
  end

  def self.with_ingredient(name)
    FoodItem.find_by!(name: name).recipes
  end

  def self.search(search)
    where(arel_table[:name].matches("%#{search}%"))
  end

  attr_reader :tag_tokens

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :recipes, through: :taggings

  def self.with_recipes_count
  	joins(:recipes).select("tags.*, COUNT(recipes.id) AS recipes_count").group("tags.id")
  end

  def self.tokens(query)
  tags = where("name like ?", "%#{query}%")
    if tags.empty?
      [{id: "<<<#{query}>>>", name: "태그 추가: \"#{query}\""}]
    else
      tags
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  def saved_to_favorites?(recipe)
  	favorites.find_by(recipe_id: recipe.id)
  end

  def save_to_favorites!(recipe)
  	favorites.create!(recipe_id: recipe.id)
  end

  def remove_from_favorites!(recipe)
  	favorites.find_by(recipe_id: recipe.id).destroy
  end

end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController

def index
	@comments = Comment.paginate(page: params[:page], per_page: 50)
end


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :require_admin



private

	def require_admin
		redirect_to root_url unless current_user.try(:admin)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_recipe
before_action :authenticate_user!

def create
	@comment = current_user.comments.build(comment_params)
	@comment.recipe = @recipe

	respond_to do |format|
		if @comment.save
			format.html { redirect_to recipe_path(@recipe) }
			format.js
		end
	end
end


def destroy
	@comment = Comment.find(params[:id])

	respond_to do |format|
		if @comment.destroy
			format.html { redirect_to recipe_path(@recipe) }
			format.js
		end
	end
end



private
	
	def set_recipe
		@recipe = Recipe.find(params[:recipe_id])
	end
	
	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tags = Tag.order(:name)
  	respond_to do |format|
  		format.html
  		format.json { render json: @tags.tokens(params[:q]) }
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
  @recipes = @user.recipes
  @favorites = @user.favorite_recipes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase unless user.blank?
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

# check if the given url has http protocol and if not, append it  
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end

  def full_name_of(user)
  	user.last_name + ' ' + user.first_name unless user.first_name.blank? && user.last_name.blank?
  end

  def full_name_with_gravatar(user)
    image_tag(gravatar_url(user), width: 20, class: "img-circle") + ' ' +
    full_name_of(user)
  end

  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def image_for(recipe)
  	if recipe.image.exists?
  		image_tag(recipe.image.url)
  	else
  		image_tag('placeholder.jpeg')
  	end
  end

  def tags_for(recipe)
  	raw recipe.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ')
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/comments/index.html.erb
<div class="container">
<h1>Admin:Comments</h1>

<div class="row">

	<div class="col-md-11">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Recipe</th>
					<th>User Name</th>
					<th>Content</th>
					<th>Created
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @comments.each do |comment| %>
				<tr>
					<td><%= comment.id %></td>
					<td><%= link_to comment.recipe.name, recipe_path(comment.recipe) %></td>
					<td><%= link_to full_name_of(comment.user), user_path(comment.user) %></td>
					<td><%= comment.content %></td>
					<td><%= comment.created_at %></td>
					<td><%= link_to 'Edit', '' %> <%= link_to 'Delete', '' %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
		<div><%= will_paginate @comments %></div>
	</div>

<div class="col-md-1">
	<%= render 'admins/nav' %>
</div>

</div>
</div>

app/views/comments/_comment.html.erb
    <div class="media">
      <a class="pull-left" href="/users/<%= comment.user.id %>">
        <%= image_tag(gravatar_url(comment.user), width: 50, class: "img-circle") %>
      </a>
      <div class="media-body">
        <div class="media-heading">
          <strong><%= link_to full_name_of(comment.user), comment.user %></strong>
        </div> 
        <p>
          <%= comment.content %>
          <br>
          <span class="muted"><%= time_ago_in_words(comment.created_at) %> ago.</span>
          
          <% if current_user == comment.user %>
          <span style="font-size:12px;">
            <%= link_to '삭제', recipe_comment_path(@recipe, comment), method: :delete, remote: true %>  
          </span>
          <% end %>
        </p>
      </div>
    </div>

app/views/comments/_form.html.erb
 <!-- Form for New Comment -->
<div class="row">
  <% if current_user %>
    <%= form_for @comment, url: recipe_comments_path(@recipe), id: 'new_comment_form', remote: true do |f| %>
    <form class="form-horizontal" role="form">
      <div class="media">
        <a class="pull-left" href="/users/<%= current_user.id %> %>">
          <%= image_tag(gravatar_url(current_user), width: 50, class: "img-circle") %>
        </a>
        <div class="media-body">
          
            <div class="input-group">
              <%= f.text_area :content, rows: 4, placeholder: '댓글을 남겨 주세요.', class: "form-control" %>
              <div style="margin:5px; float: right;">
              <%= f.submit '작성하기', class: "btn btn-danger" %>
            </div>
            </div>
          
        </div>
      </div>
    </form>
    <% end %>

    <% else %>
    <p class="comment-login">댓글을 작성하려면 <%= link_to '로그인', login_path %> 해 주세요. </p>
  <% end %>
</div>

  <!-- End Form -->

app/views/comments/create.js.erb
$('#comments_list').append('<%= j render(@comment) %>');
$('#comment_content').val('');

app/views/comments/destroy.js.erb
$('#comment-id-<%= @comment.id %>').remove();