config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  root 'static_pages#home'

  resources :admins, only: :index
  
  namespace :admins do
    resources :recipes, except: [:new, :show, :destroy]
    resources :food_items, except: [:new, :show, :destroy]
    resources :comments, only: :index
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :favorites
  end

  devise_for :users 

  devise_scope :user do
    get '/login/', to: 'devise/sessions#new', as: 'login'
    get '/signup', to: 'devise/registrations#new', as: 'signup'
    get '/settings', to: 'devise/registrations#edit', as: 'settings'
    get '/sign_in', to: 'devise/sessions#new'
  end

  resources :users

  resources :tags, only: [:index]
  resources :ingredients, only: [:autocomplete_food_item_name] do
    get :autocomplete_food_item_name, :on => :collection
  end

  resources :food_items

  resources :recipes do 
    resources :ingredients
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get 'tags/:tag' => 'recipes#index', as: :tag
  get 'ingredients/:ingredient' => 'recipes#index', as: :ingredient

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :ingredients, dependent: :destroy
  has_many :food_items, through: :ingredients
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :instructions, dependent: :destroy

  has_attached_file :image
  validates_attachment :image, 
    :content_type => { :content_type => ['image/jpeg', 'image/png']},
    :size => { :less_than => 5.megabyte }

  validates :name, presence: true
    
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc { |a| a[:food_item_name].blank? }

  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: proc { |a| a[:content].blank? }

  def self.tagged_with(name)
    Tag.find_by!(name: name).recipes
  end

  def self.with_ingredient(name)
    FoodItem.find_by!(name: name).recipes
  end

  def self.search(search)
    where(arel_table[:name].matches("%#{search}%"))
  end

  attr_reader :tag_tokens

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < ApplicationController

def index
	@recipes = Recipe.paginate(page: params[:page], per_page: 50)
end

def create
	
end

def edit
	@recipe = Recipe.find(params[:id])
end

def update
	@recipe = Recipe.find(params[:id])
	if @recipe.update(recipe_params)
		redirect_to admins_recipes_path
	else
		render :edit
	end
end

private

def recipe_params
		params.require(:recipe).permit(:name, :image, :method, :source, :tip, :serving, ingredients_attributes: [:id, :volume, :_destroy, food_item_attributes: [:id, :name, :_destroy]])
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tags = Tag.with_recipes_count
    @food_items = FoodItem.all
    @recipes = Recipe.where(nil).order('created_at desc').paginate(page: params[:page], per_page: 18)
    @recipes = @recipes.search(params[:search]) if params[:search]
    @recipes = @recipes.tagged_with(params[:tag]) if params[:tag]
    @recipes = @recipes.with_ingredient(params[:ingredient]) if params[:ingredient]
  end

  def show
    @recipe = Recipe.includes(:user, :ingredients, :food_items, :comments, :favorites, :fans).find(params[:id])
    @comment = @recipe.comments.new

  
   # Because @recipe already includes its associated entities, no more need the followings. 
   # @comments = @recipe.comments
   # @fans = @recipe.fans

    if current_user
      @current_favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    end
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.ingredients.build }
    4.times { @recipe.instructions.build }
  end

  def edit
    if @recipe.ingredients.empty?
      3.times { @recipe.ingredients.build }
    end

    if @recipe.instructions.empty?
      4.times { @recipe.instructions.build }
    end
    # Event tracking
    track_event "Editing recipe"
  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
      # Event tracking
      track_event "Recipe created"
    else
      render :new
    end

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :serving, :user, :source, :description, :image, 
        :tag_tokens,
        instructions_attributes: [:id, :content, :_destroy],
        ingredients_attributes: [:id, :food_item_name, :volume, :_destroy])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def image_for(recipe)
  	if recipe.image.exists?
  		image_tag(recipe.image.url)
  	else
  		image_tag('placeholder.jpeg')
  	end
  end

  def tags_for(recipe)
  	raw recipe.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ')
  end
end

app/views/recipes/_form.html.erb
<div class="main-container">

<script>
  mixpanel.track("Viewed Recipe Form");
</script>


<%= form_for(@recipe) do |f| %>
<!-- Error Message -->  
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>
      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- Form -->  
  <div class="input-choice">
    <div class="column1">
      <%= f.label :name, '요리 이름' %>
    </div>
    <div class="column2">
      <%= f.text_field :name, class: 'text-field' %>
    </div>
  </div>

  <div class="input-choice">
    <div class="column1">
      <%= f.label :image, '요리 사진' %>
    </div>
    <div class="column2">
      <%= f.file_field :image, class: 'file-field' %>
    </div>
  </div>

  <div class="input-choice">
    <div class="column1">
      <%= f.label :description, '간략 소개' %>
    </div>
    <div class="column2">
      <%= f.text_area :description, rows: 5  %>
    </div>
  </div>

  <div class="input-choice">
    <div class="column1">
      <%= f.label :tag_tokens, '태그' %>
    </div>
    <div class="column2">
      <%= f.text_field :tag_tokens, data: {load: @recipe.tags} %>
    </div>
  </div>

<hr>
  <div class="input-choice">
    <div class="column1">
      <%= f.label :serving, '몇 인분?' %>
    </div>
    <div class="column2">
      <%= f.number_field :serving, class: 'ingredient-field' %>
    </div>
  </div>

  <div class="input-choice">
    <div class="column1">
      <%= f.label :ingredients, '재료' %>
    </div>
    <div class="column2">
      <%= f.fields_for :ingredients do |builder| %>
      <%= render 'ingredient_fields', f: builder %>
      <% end %>
      <%= link_to_add_fields "<span class='glyphicon glyphicon-plus'></span> 필드 추가하기".html_safe, f, :ingredients %>
    </div>
  </div>

  <div class="input-choice">
    <div class="column1">
      <%= f.label :instructions, '조리법' %>
    </div>
    <div class="column2">
      <%= f.fields_for :instructions do |builder| %>
      <%= render 'instruction_fields', f: builder %>
      <% end %>
      <%= link_to_add_fields "<span class='glyphicon glyphicon-plus'></span> 필드 추가하기".html_safe, f, :instructions %>
    </div>
  </div>


  <div class="input-choice">
    <div class="column1">
      <%= f.label :source, '참고자료' %>
    </div>
    <div class="column2">
      <%= f.text_field :source, class: 'text-field' %>
    </div>
  </div>




 <div class="submit-box">
    <%= f.submit '포스트!', class: 'btn btn-danger btn-xlg' %>
  </div>
<% end %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<fieldset>
<%= f.autocomplete_field :food_item_name, autocomplete_food_item_name_ingredients_path, placeholder:'재료 이름', class: 'ingredient-field' %>
  
      <%= f.text_field :volume, placeholder: '분량', class: 'ingredient-field' %>
      <%= f.hidden_field :_destroy %>
      <%= link_to "<span class='glyphicon glyphicon-remove' style='margin-top: 12px;'></span>".html_safe, '#', class: "remove_fields" %>
      <br>
</fieldset>

app/views/recipes/_instruction_fields.html.erb
<fieldset>
    <%= f.text_area :content, rows: 3, class: 'instruction_field' %>
</fieldset>

app/views/recipes/_recipe.html.erb
<div class="recipe-item">
  <div class="grid-item-inner">
    <div class="recipe-item-image">
      <%= link_to image_for(recipe), recipe %>
    </div>
    
    <ul class="recipe-item-meta">
      <li><%= link_to truncate(recipe.name, length: 24), recipe %></li>
    </ul>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="narrow-container">
  <div class="archive-header">
	  <h1>Edit recipe</h1>
  </div>
  <div class="grid-list-container">
	<%= render 'form' %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container"> 
  <div class="archive-header">
    <!-- Set page name to append to site title -->
    <h1><%= title 'Recipes' %></h1>
      <div class="archive-subcats">
        <ul>
          <li>
            <%= link_to "전체", recipes_path, class: is_active?(recipes_path) %>
          </li>
          <% @tags.each do |tag| %>
          <li>
            <%= link_to tag.name, tag_path(tag.name), class: is_active?(tag_path(tag.name)) %> 
          </li>
        <% end %>
        </ul>
       </div>
  </div>

<script type="text/javascript">
  mixpanel.track("Viewed Recipe Index");
</script>

  <div class="grid-list-container">
    <div class="grid-list">
      <%= render @recipes %>
    </div>
  </div>

  <div>
    <%= will_paginate @recipes %> 
  </div>

</div>

app/views/recipes/index.js.erb
$('.grid-list-container').append('<%= j render(@recipes) %>');
$('.pagination').replaceWith('<%= j will_paginate(@recipes) %>');

app/views/recipes/new.html.erb
<div class="narrow-container">
  <div class="archive-header">
	  <!-- Set page name to append to site title -->
	  <h1><%= title 'Add recipe' %></h1>
  </div>
  <div class="grid-list-container">
	<%= render 'form' %>
  </div>
</div>

app/views/recipes/show.html.erb
<% @user ||= current_user  %>
<script type="text/javascript">
  mixpanel.track("Viewed Recipe", { 
    "Recipe ID": '<%= @recipe.id %>',
    "Recipe Name": '<%= @recipe.name %>'
  });
</script>

<!-- Main Image -->
<section class="teaser">
  <ul class="carousel">
    <li class="responsive-image image-loaded" style="background-image: url('<%= @recipe.image.url %>');">
    <div class="wrapper">
        <!-- Set page name to append to site title -->
        <h1><%= title @recipe.name %></h1>
        <%= link_to full_name_with_gravatar(@recipe.user), @recipe.user %>
    </div>
  </ul>
</section>

<div style="clear:both"></div>

<div class="wrap rec-heading">

<!--  Description & Tags -->

  <div class="rec-main">
    <div class="archive-subcats">
      <ul>
        <% @recipe.tags.each do |tag| %>
          <li>
            <%= link_to tag.name, tag_path(tag.name), class: is_active?(tag_path(tag.name)) %> 
          </li>
        <% end %>
      </ul>
    </div>
    <p>
      <%= @recipe.description %>
    </p>
  </div>

  <div class="rec-sidebar">
    <h3>Add to Fav</h3>
<!--  Fan Box -->
      <% if @recipe.fans.any?  %>
        <% @recipe.fans.each do |fan| %>
          <div class="fan">
            <%= image_tag(gravatar_url(fan), width: 50, class: "img-circle")%>
          </div>
        <% end  %>
      <% else  %>
        <p>아직 팬이 없습니다.</p>
      <% end %>

<!--  Add to Fav Button -->
      <% unless @user.nil? %>
        <% if @user.saved_to_favorites?(@recipe) %>
          <div>
            <%= button_to "저장 취소하기", recipe_favorite_path(@recipe, @current_favorite), method: :delete, class: 'btn btn-lg btn-default' %>
          </div>
        <% else %>
          <div>
            <%= button_to '레시피 저장하기', recipe_favorites_path(@recipe), class: 'btn btn-lg btn-danger' %>
          </div>
        <% end %>
      <% end %>
  </div>

<div class="wrap rec-heading">
<!--  Instructions -->
  <div class="rec-main">
    <h3>Instructions</h3>
      <% if @recipe.instructions.any?  %>
        <ol>
          <% @recipe.instructions.each do |instruction|  %>
          <li><p> <%= instruction.content %> </p></li>
          <% end  %>
        </ol>
      <% end %>

      <% unless @recipe.source.blank?  %> 
        <span style="font-size:16px;">참고 | <%= @recipe.source %></span>
      <% end  %>


<!--  Edit/Destroy -->
    <% if @user.try(:admin?) %>
    <div class="admin_console">
      <br>
      <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
      <%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>  
  </div>

<!--  Ingredients -->
  <div class="rec-sidebar">
    <h3>Ingredients</h3>
    <strong>+ <%= @recipe.serving %>인분</strong>
    <% if @recipe.ingredients.any?  %>
      <ul> 
        <% @recipe.ingredients.each do |ingredient|  %>
        <li> <%= link_to ingredient.food_item.name, ingredient_path(ingredient.food_item.name) %> 
            <%= ingredient.volume %>
        </li>
        <% end  %>
      </ul>   
    <% end  %>
  </div>
</div>

<!--  Comment -->

<div class="wrap rec-heading">
  <div class="rec-main">

    <div id="comments_count">
      <h3><%= pluralize(@recipe.comments.count, 'comment') %></h3>
    </div>
  
    <% unless @recipe.comments.blank? %>
      <div class="row">
        <div id="comments_list">
        <% @recipe.comments.each do |comment| %>
        <% unless comment.user.blank? %>
        <div class="media" id="comment-id-<%= comment.id %>">
        <a class="pull-left" href="#">
          <%= image_tag(gravatar_url(comment.user), width: 50, class: "img-circle") %>
        </a>
        <div class="media-body">
          <div class="media-heading">
            <strong><%= link_to full_name_of(comment.user), comment.user %></strong>
          </div> 
          <p>
            <%= comment.content %>
            <br>
            <span class="muted"><%= time_ago_in_words(comment.created_at) %> ago</span>
            
            <% if @user == comment.user %>
            <span style="font-size:12px;">
              <%= link_to '삭제', recipe_comment_path(@recipe, comment), method: :delete, remote: true %>  
            </span>
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>

 <%= render 'comments/form' %>
</div>
</div>