config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  root 'static_pages#home'

  resources :admins, only: :index
  
  namespace :admins do
    resources :recipes, except: [:new, :show, :destroy]
    resources :food_items, except: [:new, :show, :destroy]
    resources :comments, only: :index
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :favorites
  end

  devise_for :users 

  devise_scope :user do
    get '/login/', to: 'devise/sessions#new', as: 'login'
    get '/signup', to: 'devise/registrations#new', as: 'signup'
    get '/settings', to: 'devise/registrations#edit', as: 'settings'
    get '/sign_in', to: 'devise/sessions#new'
  end

  resources :users

  resources :tags, only: [:index]
  resources :ingredients, only: [:autocomplete_food_item_name] do
    get :autocomplete_food_item_name, :on => :collection
  end

  resources :food_items

  resources :recipes do 
    resources :ingredients
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get 'tags/:tag' => 'recipes#index', as: :tag
  get 'ingredients/:ingredient' => 'recipes#index', as: :ingredient

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  def saved_to_favorites?(recipe)
  	favorites.find_by(recipe_id: recipe.id)
  end

  def save_to_favorites!(recipe)
  	favorites.create!(recipe_id: recipe.id)
  end

  def remove_from_favorites!(recipe)
  	favorites.find_by(recipe_id: recipe.id).destroy
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

def index
	@users = User.paginate(page: params[:page], per_page: 50)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
  @recipes = @user.recipes
  @favorites = @user.favorite_recipes
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/index.html.erb
<div class="container">
<h1>Admin:Users</h1>

<div class="row">

	<div class="col-md-11">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Full Name</th>
					<th>Email</th>
					<th>Recipes Created</th>
					<th>Comments Left</th>
					<th>Signin Count</th>
					<th>Signup Date</th>
					<th>Last Signin IP</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= user.id %></td>
					<td><%= link_to full_name_of(user), user_path(user) %></td>
					<td><%= user.email %></td>
					<td><%= user.recipes.count %></td>
					<td><%= user.comments.count %></td>
					<td><%= user.sign_in_count %></td>
					<td><%= user.created_at %></td>
					<td><%= user.last_sign_in_ip %></td>
					<td><%= link_to 'Edit', edit_admins_user_path(user) %> <%= link_to 'Delete', '' %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
		<div><%= will_paginate @users %></div>
	</div>

<div class="col-md-1">
	<%= render 'admins/nav' %>
</div>

</div>
</div>