config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  root 'static_pages#home'

  resources :admins, only: :index
  
  namespace :admins do
    resources :recipes, except: [:new, :show, :destroy]
    resources :food_items, except: [:new, :show, :destroy]
    resources :comments, only: :index
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :favorites
  end

  devise_for :users 

  devise_scope :user do
    get '/login/', to: 'devise/sessions#new', as: 'login'
    get '/signup', to: 'devise/registrations#new', as: 'signup'
    get '/settings', to: 'devise/registrations#edit', as: 'settings'
    get '/sign_in', to: 'devise/sessions#new'
  end

  resources :users

  resources :tags, only: [:index]
  resources :ingredients, only: [:autocomplete_food_item_name] do
    get :autocomplete_food_item_name, :on => :collection
  end

  resources :food_items

  resources :recipes do 
    resources :ingredients
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get 'tags/:tag' => 'recipes#index', as: :tag
  get 'ingredients/:ingredient' => 'recipes#index', as: :ingredient

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :ingredients, dependent: :destroy
  has_many :food_items, through: :ingredients
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :instructions, dependent: :destroy

  has_attached_file :image
  validates_attachment :image, 
    :content_type => { :content_type => ['image/jpeg', 'image/png']},
    :size => { :less_than => 5.megabyte }

  validates :name, presence: true
    
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc { |a| a[:food_item_name].blank? }

  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: proc { |a| a[:content].blank? }

  def self.tagged_with(name)
    Tag.find_by!(name: name).recipes
  end

  def self.with_ingredient(name)
    FoodItem.find_by!(name: name).recipes
  end

  def self.search(search)
    where(arel_table[:name].matches("%#{search}%"))
  end

  attr_reader :tag_tokens

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < ApplicationController

def index
	@recipes = Recipe.paginate(page: params[:page], per_page: 50)
end

def create
	
end

def edit
	@recipe = Recipe.find(params[:id])
end

def update
	@recipe = Recipe.find(params[:id])
	if @recipe.update(recipe_params)
		redirect_to admins_recipes_path
	else
		render :edit
	end
end

private

def recipe_params
		params.require(:recipe).permit(:name, :image, :method, :source, :tip, :serving, ingredients_attributes: [:id, :volume, :_destroy, food_item_attributes: [:id, :name, :_destroy]])
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tags = Tag.with_recipes_count
    @food_items = FoodItem.all
    @recipes = Recipe.where(nil).order('created_at desc').paginate(page: params[:page], per_page: 18)
    @recipes = @recipes.search(params[:search]) if params[:search]
    @recipes = @recipes.tagged_with(params[:tag]) if params[:tag]
    @recipes = @recipes.with_ingredient(params[:ingredient]) if params[:ingredient]
  end

  def show
    @recipe = Recipe.includes(:user, :ingredients, :food_items, :comments, :favorites, :fans).find(params[:id])
    @comment = @recipe.comments.new

  
   # Because @recipe already includes its associated entities, no more need the followings. 
   # @comments = @recipe.comments
   # @fans = @recipe.fans

    if current_user
      @current_favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    end
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.ingredients.build }
    4.times { @recipe.instructions.build }
  end

  def edit
    if @recipe.ingredients.empty?
      3.times { @recipe.ingredients.build }
    end

    if @recipe.instructions.empty?
      4.times { @recipe.instructions.build }
    end
    # Event tracking
    track_event "Editing recipe"
  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
      # Event tracking
      track_event "Recipe created"
    else
      render :new
    end

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :serving, :user, :source, :description, :image, 
        :tag_tokens,
        instructions_attributes: [:id, :content, :_destroy],
        ingredients_attributes: [:id, :food_item_name, :volume, :_destroy])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def image_for(recipe)
  	if recipe.image.exists?
  		image_tag(recipe.image.url)
  	else
  		image_tag('placeholder.jpeg')
  	end
  end

  def tags_for(recipe)
  	raw recipe.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ')
  end
end

app/views/admins/recipes/_form.html.erb
<%= form_for @recipe, url: admins_recipe_path do |f| %>
<form class="form-horizontal" role="form">
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Recipe Meta</h3>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :method %><br>
    <%= f.text_area :method, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :source %><br>
    <%= f.text_field :source, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :serving %><br>
    <%= f.text_field :serving, class: 'form-control' %>
  </div>

  <hr>
   <h3>Ingredients</h3>
  <!-- Begin form for recipe's ingredients -->
    <%= f.fields_for :ingredients do |i| %>
      <div class="form-group">
        <%= i.fields_for :food_item do |builder| %>
          <%= builder.text_field :name, placeholder: 'Food Item' %>
        <% end %>
        
        <%= i.text_field :volume, placeholder: 'Volume' %>
        <%= i.check_box :_destroy %>

        <%= f.label :_destroy, "Remove Ingredient" %>
      </div>
    <% end %>


  <div class="actions">
    <%= f.submit class: 'btn btn-lg btn-primary' %>
  </div>

</form>
<% end %>

app/views/admins/recipes/edit.html.erb
<div class="container">
<h1>Editing <%= @recipe.name %></h1>

<%= render 'form' %>
</div>

app/views/admins/recipes/index.html.erb
<div class="container">
<h1>Admin:Recipes</h1>

<div class="row">

	<div class="col-md-11">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>User Created</th>
					<th>Comments Left</th>
					<th>Fav Added</th>
					<th>Created</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @recipes.each do |recipe| %>
				<tr>
					<td><%= recipe.id %></td>
					<td><%= link_to recipe.name, recipe_path(recipe) %></td>
					<td><%= link_to full_name_of(recipe.user), user_path(recipe.user) %></td>
					<td><%= recipe.comments.count %></td>
					<td><%= recipe.fans.count %></td>
					<td><%= recipe.created_at %></td>
					<td>
						<%= link_to 'Show', recipe_path(recipe) %>
						<%= link_to 'Edit', edit_admins_recipe_path(recipe) %>
						<%= link_to 'Delete', '' %>
					</td>
				</tr>
			</tbody>
			<% end %>
		</table>
	<div><%= will_paginate @recipes %></div>
	</div>

<div class="col-md-1">
	<%= render 'admins/nav' %>
</div>

</div>
</div>